CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL,
  "lastname" varchar(30) UNIQUE NOT NULL,
  "email" varchar(30) UNIQUE NOT NULL,
  "password" varchar(30) UNIQUE NOT NULL,
  "age" int UNIQUE NOT NULL,
  "role" int NOT NULL,
  "courses" int NOT NULL
);

CREATE TABLE "course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "description" varchar(25) NOT NULL,
  "level" int NOT NULL,
  "categorie" int NOT NULL
);

CREATE TABLE "courses_video_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courses" int NOT NULL,
  "videos" int NOT NULL
);

CREATE TABLE "video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "url" varchar(100) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

ALTER TABLE "course" ADD FOREIGN KEY ("level") REFERENCES "level" ("id");

ALTER TABLE "courses_video_courses" ADD FOREIGN KEY ("videos") REFERENCES "video" ("id");

ALTER TABLE "course" ADD FOREIGN KEY ("categorie") REFERENCES "categories" ("id");

ALTER TABLE "courses_video_courses" ADD FOREIGN KEY ("courses") REFERENCES "course" ("id");

ALTER TABLE "user" ADD FOREIGN KEY ("role") REFERENCES "roles" ("id");

ALTER TABLE "user" ADD FOREIGN KEY ("courses") REFERENCES "courses_video_courses" ("id");
